'use client';
/* oxlint-disable next/no-img-element -- Display the original panorama assets without image-service recompression. */
import {useEffect,useRef,useState} from 'react';
import {MapPin,PersonStanding,PanelsTopLeft,House,ReceiptText,Music2,Ellipsis,Expand,Share2,Heart,Flame,ChevronDown,ChevronUp,RotateCcw,Languages,MonitorSmartphone,Box,Check,VolumeX} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Panorama,clamp,project,type View} from './panorama';
type Scene={id:string;key:string;title:string;floor:number;faces:Record<string,string>;previewFaces?:Record<string,string>;thumbnail?:string;position:{x:number;y:number};mapRotation:number;view:{hlookat?:number;vlookat?:number;fov?:number};hotspots:{id:string;title:string;target:string;yaw:number;pitch:number}[];products:{id:string;title:string}[]};
type Floor={id:number;name:string;plan:string;navigation:string;start:string};
type Tour={title:string;source:string;defaultScene:string;floors:Floor[];scenes:Scene[]};
export default function Home(){
 const canvas=useRef<HTMLCanvasElement>(null),engine=useRef<Panorama|null>(null),view=useRef<View>({yaw:0,pitch:0,fov:110}),active=useRef<Scene|null>(null),auto=useRef(true),points=useRef(new Map<number,{x:number;y:number}>()),last=useRef({x:0,y:0,dist:0}),keys=useRef(new Set<string>()),frame=useRef(0),hotspotEls=useRef(new Map<string,HTMLButtonElement>()),heading=useRef<HTMLDivElement>(null);
 const [tour,setTour]=useState<Tour|null>(null),[scene,setScene]=useState<Scene|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[mode,setMode]=useState('pano'),[map,setMap]=useState(true),[rooms,setRooms]=useState(false),[dialog,setDialog]=useState(''),[rotation,setRotation]=useState(true),[liked,setLiked]=useState(false),[copied,setCopied]=useState(false),[english,setEnglish]=useState(false),[retry,setRetry]=useState(0);
 const [detailError,setDetailError]=useState(false),[music,setMusic]=useState(false);const audio=useRef<HTMLAudioElement|null>(null);
 const label=(cn:string,en:string)=>english?en:cn;
 const choose=(s:Scene)=>{auto.current=false;setRotation(false);setMode('pano');setScene(s);setRooms(false);const url=new URL(location.href);url.searchParams.set('scene',s.key);history.replaceState(null,'',url);};
 useEffect(()=>{let dead=false;fetch(import.meta.env.BASE_URL+'tour.json?v=146').then(r=>{if(!r.ok)throw Error('方案加载失败');return r.json() as Promise<Tour>;}).then((t:Tour)=>{if(dead)return;setTour(t);const key=new URLSearchParams(location.search).get('scene');setScene(t.scenes.find(s=>s.key===key)||t.scenes.find(s=>s.id===t.defaultScene)||t.scenes[0]);}).catch(e=>setError(String(e.message)));return()=>{dead=true;};},[retry]);
 useEffect(()=>{if(!canvas.current)return;try{engine.current=new Panorama(canvas.current);}catch(e){queueMicrotask(()=>setError((e as Error).message));return;}
 let prev=performance.now();const animate=(now:number)=>{const dt=Math.min((now-prev)/1000,.05);prev=now;if(auto.current&&!points.current.size)view.current.yaw+=dt*3;const k=keys.current;if(k.has('arrowleft')||k.has('a'))view.current.yaw-=dt*35;if(k.has('arrowright')||k.has('d'))view.current.yaw+=dt*35;if(k.has('arrowup')||k.has('w'))view.current.pitch=clamp(view.current.pitch-dt*28,-85,85);if(k.has('arrowdown')||k.has('s'))view.current.pitch=clamp(view.current.pitch+dt*28,-85,85);engine.current?.draw(view.current);const rect=canvas.current?.getBoundingClientRect();if(rect&&active.current){for(const h of active.current.hotspots){const el=hotspotEls.current.get(h.id);if(!el)continue;const p=project(h.yaw,h.pitch,view.current,rect.width,rect.height);el.style.display=p&&p.x>-80&&p.x<rect.width+80&&p.y>0&&p.y<rect.height?'':'none';if(p)el.style.transform=`translate(${p.x}px,${p.y}px) translate(-50%,-50%)`;}}if(heading.current)heading.current.style.transform=`translate(-50%,-50%) rotate(${view.current.yaw+(active.current?.mapRotation||0)}deg)`;frame.current=requestAnimationFrame(animate);};frame.current=requestAnimationFrame(animate);
 const wheel=(e:WheelEvent)=>{e.preventDefault();auto.current=false;setRotation(false);view.current.fov=clamp(view.current.fov+e.deltaY*.045,55,120);};canvas.current.addEventListener('wheel',wheel,{passive:false});const el=canvas.current;return()=>{cancelAnimationFrame(frame.current);el.removeEventListener('wheel',wheel);engine.current?.dispose();};},[]);
 useEffect(()=>{if(!scene||!engine.current)return;let dead=false;active.current=scene;queueMicrotask(()=>{if(!dead){setLoading(true);setDetailError(false);setError('');}});
 engine.current.load(scene.faces,scene.previewFaces,()=>{if(dead)return;view.current={yaw:scene.view.hlookat||0,pitch:scene.view.vlookat||0,fov:scene.view.fov||110};engine.current?.draw(view.current);setLoading(false);},()=>{if(!dead)setDetailError(true);}).catch(e=>{if(!dead)setError(e.name==='AbortError'?'图片加载超时，请重试。':e.message);});
 return()=>{dead=true;};},[scene,retry]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('button,input,[role=dialog],[role=menu]'))return;const key=e.key.toLowerCase();if(['arrowleft','arrowright','arrowup','arrowdown','w','a','s','d'].includes(key)){e.preventDefault();auto.current=false;setRotation(false);keys.current.add(key);}};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());const blur=()=>keys.current.clear();window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);};},[]);
 function pointerDown(e:React.PointerEvent<HTMLCanvasElement>){e.currentTarget.focus();e.currentTarget.setPointerCapture(e.pointerId);auto.current=false;setRotation(false);points.current.set(e.pointerId,{x:e.clientX,y:e.clientY});last.current={x:e.clientX,y:e.clientY,dist:0};if(points.current.size===2){const p=[...points.current.values()];last.current.dist=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);}}
 function pointerMove(e:React.PointerEvent<HTMLCanvasElement>){if(!points.current.has(e.pointerId))return;points.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(points.current.size===2){const p=[...points.current.values()],dist=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);if(last.current.dist)view.current.fov=clamp(view.current.fov*last.current.dist/dist,55,120);last.current.dist=dist;}else{const scale=view.current.fov/Math.max(e.currentTarget.clientWidth,e.currentTarget.clientHeight);view.current.yaw-=(e.clientX-last.current.x)*scale;view.current.pitch=clamp(view.current.pitch-(e.clientY-last.current.y)*scale,-85,85);}last.current.x=e.clientX;last.current.y=e.clientY;}
 function pointerUp(e:React.PointerEvent<HTMLCanvasElement>){points.current.delete(e.pointerId);const rem=[...points.current.values()][0];if(rem)last.current={...rem,dist:0};}
 const floor=tour?.floors.find(f=>f.id===scene?.floor);const floorScenes=tour?.scenes.filter(s=>s.floor===scene?.floor)||[];
 async function share(){setCopied(false);setDialog('share');}
 async function toggleMusic(){
  if(music){audio.current?.pause();setMusic(false);return;}
  if(!audio.current){audio.current=new Audio('https://panojson-oss.kujiale.com/pano/pano-editor/2026/09/07/NKPIDIYKTIVXMAABAAAAADA8.mp3');audio.current.loop=true;audio.current.volume=.25;}
  try{await audio.current.play();setMusic(true);}catch{setDialog('music');}
 }
 useEffect(()=>()=>{audio.current?.pause();},[]);

 return <main className="tour-shell" aria-label="95平户型全景">
  <canvas ref={canvas} className="panorama" aria-label="全景画面，可拖动转向，滚轮或双指缩放" tabIndex={0} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}/>
  {mode==='pano'&&!loading&&scene&&<div className="hotspots">{scene.hotspots.map(h=><button key={h.id} ref={el=>{if(el)hotspotEls.current.set(h.id,el);else hotspotEls.current.delete(h.id);}} className="hotspot" onClick={()=>{const s=tour?.scenes.find(s=>s.id===h.target);if(s)choose(s);}} aria-label={'进入'+h.title}><span>{h.title||label('前往房间','Go to room')}</span><ChevronUp/></button>)}</div>}
  {mode==='plan'&&floor&&<div className="plan-view"><img src={floor.plan} alt={floor.name+'平面户型图'}/><div className="plan-floors">{tour?.floors.map(f=><button className={f.id===floor.id?'selected':''} key={f.id} onClick={()=>{const s=tour.scenes.find(s=>s.id===f.start);if(s){setScene(s);auto.current=false;}}}>{f.name}</button>)}</div></div>}
  {map&&floor&&<aside className="mini-map glass" aria-label="户型导航"><div className="map-head"><span><MapPin size={16} fill="currentColor"/>{scene?.title}</span><DropdownMenu><DropdownMenuTrigger className="floor-select">{floor.name}<ChevronDown size={13}/></DropdownMenuTrigger><DropdownMenuContent className="floor-menu">{tour?.floors.map(f=><DropdownMenuItem key={f.id} onClick={()=>{const s=tour.scenes.find(s=>s.id===f.start);if(s)choose(s);}}>{f.name}{f.id===floor.id&&<Check size={14}/>}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></div><div className="map-body"><img src={floor.navigation} alt={floor.name+'导航图'}/>{floorScenes.map(s=>s.id===scene?.id?<div key={s.id} ref={heading} className="view-cone" style={{left:s.position.x*100+'%',top:s.position.y*100+'%'}}><i/></div>:<button className="map-pin" key={s.id} title={s.title} aria-label={'切换到'+s.title} style={{left:s.position.x*100+'%',top:s.position.y*100+'%'}} onClick={()=>choose(s)}><MapPin fill="white" size={23}/></button>)}<span className="map-grip"/></div></aside>}
  <Tabs className="mode-tabs" value={mode} onValueChange={v=>setMode(String(v))}><TabsList className="mode-list glass"><TabsTrigger value="pano"><PersonStanding/>{label('漫游','Tour')}</TabsTrigger><TabsTrigger value="plan"><PanelsTopLeft/>{label('平面户型','Floor plan')}</TabsTrigger></TabsList></Tabs>
  <aside className="right-tools"><span className="views glass"><Flame size={12} fill="currentColor"/>147</span><button className="round glass" title="全屏" aria-label="全屏" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen().catch(()=>setDialog('fullscreen'));}}><Expand/></button><button className="round glass" title="分享" aria-label="分享" onClick={share}><Share2/></button><button className={'round glass '+(liked?'liked':'')} title="收藏" aria-label={liked?'取消收藏':'收藏'} onClick={()=>setLiked(!liked)}><Heart fill="currentColor"/></button></aside>
  {rooms&&<section className="room-tray glass" aria-label="房间选择">{tour?.floors.map(f=><div className="room-floor" key={f.id}><h2>{f.name}</h2><div>{tour.scenes.filter(s=>s.floor===f.id).map((s,i)=><button key={s.id} className={'room-card '+(s.id===scene?.id?'selected':'')} onClick={()=>choose(s)}><img src={s.thumbnail||s.previewFaces?.f||s.faces.f} loading="lazy" decoding="async" alt=""/><span>{s.title}{tour.scenes.filter(a=>a.title===s.title).length>1?' · '+(i+1):''}</span></button>)}</div></div>)}</section>}
  <footer className="bottom-bar glass"><nav aria-label="全景工具"><button className={rooms?'active':''} onClick={()=>setRooms(!rooms)}><House/><span>{label('房间选择','Rooms')}</span></button><button onClick={()=>setDialog('products')}><ReceiptText/><span>{label('商品清单','Products')}</span></button><button className={map?'active':''} onClick={()=>setMap(!map)}><PanelsTopLeft/><span>{label('户型导航','Navigation')}</span></button><button onClick={toggleMusic}>{music?<Music2/>:<VolumeX/>}<span>{label(music?'音乐开':'音乐关',music?'Sound on':'Sound off')}</span></button><DropdownMenu><DropdownMenuTrigger className="more-trigger"><Ellipsis fill="rgba(255,255,255,.5)"/><span>{label('更多','More')}</span></DropdownMenuTrigger><DropdownMenuContent className="more-menu glass" side="top" align="end" sideOffset={16}><DropdownMenuItem onClick={()=>setDialog('multi')}><MonitorSmartphone/><span>{label('多屏联动','Multi screen')}</span></DropdownMenuItem><DropdownMenuItem onClick={()=>setEnglish(!english)}><Languages/><span>{label('中英切换','中文 / English')}</span></DropdownMenuItem><DropdownMenuItem onClick={()=>{auto.current=!rotation;setRotation(!rotation);}}><RotateCcw/><span>{label(rotation?'停止旋转':'自动旋转',rotation?'Stop rotation':'Auto rotate')}</span></DropdownMenuItem><DropdownMenuItem onClick={()=>{setMode('plan');}}><Box/><span>{label('方案预览','Plan preview')}</span></DropdownMenuItem></DropdownMenuContent></DropdownMenu></nav></footer>
  {loading&&!error&&<output className="load-indicator"><i/>{label('全景加载中','Loading panorama')}</output>}
  {detailError&&!loading&&!error&&<button className="load-indicator" onClick={()=>setRetry(v=>v+1)}>高清暂未加载，点击重试</button>}
  {error&&<div className="error-panel" role="alert"><p>{error}</p><button onClick={()=>{setError('');setRetry(v=>v+1);}}>重新加载</button></div>}
  <Dialog open={!!dialog} onOpenChange={open=>{if(!open)setDialog('');}}><DialogContent className={dialog==='products'?'products-dialog':'tour-dialog'}><DialogTitle>{dialog==='products'?label('商品清单','Products'):dialog==='share'?label('分享当前房间','Share this room'):dialog==='multi'?'多屏联动':dialog==='music'?'背景音乐':'全屏浏览'}</DialogTitle><DialogDescription>{dialog==='products'?'原方案公开的商品与材料信息':dialog==='share'?'复制链接可打开当前房间。':dialog==='multi'?'在另一台设备打开本页面链接，即可浏览同一方案。':dialog==='music'?'原站音乐暂时无法播放，请稍后重试。':'当前浏览器不支持网页全屏，可使用浏览器自带的全屏功能。'}</DialogDescription>{dialog==='products'&&<div className="product-list">{scene?.products.map((p,i)=><div key={p.id}><span>{String(i+1).padStart(2,'0')}</span><p>{p.title}</p></div>)}</div>}{(dialog==='share'||dialog==='multi')&&<div className="share-content"><input readOnly value={typeof location!=='undefined'?location.href:''} aria-label="当前房间链接" onFocus={e=>e.target.select()}/><button onClick={()=>{void navigator.clipboard.writeText(location.href).then(()=>setCopied(true)).catch(()=>setCopied(false));}}>{copied?'已复制':'复制链接'}</button></div>}</DialogContent></Dialog>
 </main>;
}
